name: minima_note_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.0
  path_provider: ^2.0.13
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0
  change_app_package_name: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
        - asset: assets/fonts/MontserratAlternates-Medium.ttf
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/MontserratAlternates-SemiBold.ttf


